# Create following features for a progress bar:
    - Add button: to add a new bar
    - Start button: on clicking it, the bar starts getting filled with a color and gets filled completely in 2 seconds.
    - Reset button: clean slate- remove all the bars.
    - Tricky part: If 3 bars are getting filled at once no new bar will get activated to get filled with color.




PS: Asked in Urbint(Itron) SDE-2 role interview on 13-12-2025